-- Supabase schema for hybrid SEO rank tracking (DB + CSV)
-- Apply in Supabase SQL editor.

create table if not exists public.seo_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  expected_url text,
  expected_title text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seo_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  run_timestamp timestamptz not null,
  start_date date not null,
  end_date date not null,
  site_url text not null,
  found_count integer not null default 0,
  not_found_count integer not null default 0,
  serp_success integer not null default 0,
  serp_failures integer not null default 0,
  serp_considered integer not null default 0,
  status text not null default 'success',
  created_at timestamptz not null default now()
);

create table if not exists public.seo_rank_history (
  id bigint generated by default as identity primary key,
  run_id bigint references public.seo_runs(id) on delete set null,
  timestamp timestamptz not null,
  start_date date not null,
  end_date date not null,
  source text not null check (source in ('gsc', 'serpapi')),
  keyword_id bigint references public.seo_keywords(id) on delete set null,
  keyword text not null,
  rank_label text not null default '',
  rank_value integer,
  avg_position numeric(10, 2),
  impressions bigint,
  clicks bigint,
  ctr numeric(10, 4),
  matched_page text,
  expected_page text,
  top_domain text,
  top_title text,
  total_results bigint,
  created_at timestamptz not null default now()
);

create unique index if not exists seo_rank_history_idempotency_key
  on public.seo_rank_history (timestamp, source, keyword, start_date, end_date);

create index if not exists seo_rank_history_timestamp_idx
  on public.seo_rank_history (timestamp);

create index if not exists seo_rank_history_keyword_idx
  on public.seo_rank_history (keyword);

create index if not exists seo_rank_history_source_idx
  on public.seo_rank_history (source);

create index if not exists seo_rank_history_keyword_timestamp_idx
  on public.seo_rank_history (keyword, timestamp);

create or replace function public.seo_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists seo_keywords_set_updated_at on public.seo_keywords;
create trigger seo_keywords_set_updated_at
before update on public.seo_keywords
for each row
execute function public.seo_set_updated_at();

create or replace view public.seo_kpi_snapshots as
with gsc_rows as (
  select
    timestamp,
    keyword,
    rank_value,
    avg_position,
    coalesce(impressions, 0) as impressions,
    coalesce(clicks, 0) as clicks
  from public.seo_rank_history
  where source = 'gsc'
)
select
  timestamp,
  count(*)::bigint as keywords_tracked,
  count(rank_value)::bigint as keywords_found,
  count(*) filter (where rank_value <= 3)::bigint as top_3,
  count(*) filter (where rank_value <= 10)::bigint as top_10,
  count(*) filter (where rank_value <= 30)::bigint as top_30,
  (count(*) - count(rank_value))::bigint as not_found,
  round(avg(rank_value)::numeric, 2) as avg_rank,
  round(avg(avg_position)::numeric, 2) as avg_position,
  sum(impressions)::bigint as total_impressions,
  sum(clicks)::bigint as total_clicks,
  case
    when sum(impressions) > 0
      then round((sum(clicks)::numeric / sum(impressions)::numeric) * 100, 2)
    else 0
  end as ctr_percent
from gsc_rows
group by timestamp
order by timestamp;

create or replace view public.seo_keyword_trends as
select
  timestamp,
  keyword,
  rank_label,
  rank_value,
  avg_position,
  impressions,
  clicks,
  ctr,
  matched_page,
  expected_page
from public.seo_rank_history
where source = 'gsc'
order by keyword, timestamp;

create or replace view public.seo_top_movers_30d as
with scoped as (
  select
    keyword,
    timestamp,
    rank_value,
    row_number() over (partition by keyword order by timestamp asc) as rn_first,
    row_number() over (partition by keyword order by timestamp desc) as rn_last
  from public.seo_rank_history
  where source = 'gsc'
    and rank_value is not null
    and timestamp >= now() - interval '30 days'
),
pivoted as (
  select
    keyword,
    max(case when rn_first = 1 then rank_value end) as first_rank,
    max(case when rn_last = 1 then rank_value end) as latest_rank,
    max(case when rn_last = 1 then timestamp end) as latest_timestamp
  from scoped
  group by keyword
)
select
  keyword,
  first_rank,
  latest_rank,
  (first_rank - latest_rank) as rank_delta,
  latest_timestamp
from pivoted
where first_rank is not null
  and latest_rank is not null
order by rank_delta desc, latest_timestamp desc;

create or replace view public.seo_okr_snapshots as
select
  timestamp,
  keywords_tracked,
  keywords_found,
  top_3,
  top_10,
  top_30,
  not_found,
  avg_rank,
  avg_position,
  total_impressions,
  total_clicks,
  ctr_percent,
  case
    when keywords_tracked > 0
      then round((keywords_found::numeric / keywords_tracked::numeric) * 100, 2)
    else 0
  end as found_rate_pct,
  case
    when keywords_tracked > 0
      then round((top_3::numeric / keywords_tracked::numeric) * 100, 2)
    else 0
  end as top3_share_pct,
  case
    when keywords_tracked > 0
      then round((top_10::numeric / keywords_tracked::numeric) * 100, 2)
    else 0
  end as top10_share_pct,
  case
    when keywords_tracked > 0
      then round((top_30::numeric / keywords_tracked::numeric) * 100, 2)
    else 0
  end as top30_share_pct
from public.seo_kpi_snapshots;

create or replace view public.seo_okr_latest as
with latest as (
  select *
  from public.seo_okr_snapshots
  order by timestamp desc
  limit 1
),
baseline as (
  select *
  from public.seo_okr_snapshots
  where timestamp <= (select timestamp from latest) - interval '30 days'
  order by timestamp desc
  limit 1
)
select
  l.timestamp as latest_timestamp,
  l.keywords_tracked,
  l.keywords_found,
  l.found_rate_pct,
  l.top3_share_pct,
  l.top10_share_pct,
  l.top30_share_pct,
  l.avg_rank,
  l.avg_position,
  l.total_impressions,
  l.total_clicks,
  l.ctr_percent,
  b.timestamp as baseline_timestamp,
  b.avg_rank as baseline_avg_rank,
  b.top10_share_pct as baseline_top10_share_pct,
  b.total_impressions as baseline_total_impressions,
  b.total_clicks as baseline_total_clicks,
  b.ctr_percent as baseline_ctr_percent,
  case
    when b.avg_rank is not null then round(b.avg_rank - l.avg_rank, 2)
    else null
  end as avg_rank_delta_30d,
  case
    when b.top10_share_pct is not null then round(l.top10_share_pct - b.top10_share_pct, 2)
    else null
  end as top10_share_delta_30d_pct,
  case
    when b.total_impressions is not null and b.total_impressions > 0
      then round(((l.total_impressions - b.total_impressions)::numeric / b.total_impressions::numeric) * 100, 2)
    else null
  end as impressions_growth_30d_pct,
  case
    when b.total_clicks is not null and b.total_clicks > 0
      then round(((l.total_clicks - b.total_clicks)::numeric / b.total_clicks::numeric) * 100, 2)
    else null
  end as clicks_growth_30d_pct,
  case
    when b.ctr_percent is not null then round(l.ctr_percent - b.ctr_percent, 2)
    else null
  end as ctr_delta_30d_pct_points
from latest l
left join baseline b on true;

-- Optional read-only role for BI tools (Looker Studio / Metabase / etc.)
-- Replace <strong-password> before running.
--
-- create role seo_readonly login password '<strong-password>';
-- grant usage on schema public to seo_readonly;
-- grant select on public.seo_keywords, public.seo_runs, public.seo_rank_history to seo_readonly;
-- grant select on public.seo_kpi_snapshots, public.seo_keyword_trends, public.seo_top_movers_30d to seo_readonly;
-- grant select on public.seo_okr_snapshots, public.seo_okr_latest to seo_readonly;
-- alter default privileges in schema public grant select on tables to seo_readonly;
